# -*- coding: utf-8 -*-
"""INGREGUARD - MINOR PROJECT  .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mhrYlYum8uOCCoqMZV0E8oXYxfDv_lm4

LOADING THE DATSET
"""

import pandas as pd
import numpy as np

# Load ingredient dataset
ingredient_df = pd.read_csv("/content/ingredientsList.csv")

print("Dataset shape:", ingredient_df.shape)
ingredient_df.head()

"""DATA PREPROCESSING"""

# Check missing values
print("Missing values:\n", ingredient_df.isnull().sum())

# Drop duplicate rows
ingredient_df.drop_duplicates(inplace=True)

# Fill missing text fields
text_columns = [
    "name",
    "scientific_name",
    "short_description",
    "what_is_it",
    "what_does_it_do"
]

for col in text_columns:
    ingredient_df[col] = ingredient_df[col].fillna("not available")

# Standardize ingredient name text
ingredient_df["name"] = ingredient_df["name"].str.lower().str.strip()

print("After preprocessing:", ingredient_df.shape)

"""GENERATING SYNTHETIC DATASET"""

import pandas as pd

contexts = [
    "pregnancy safety analysis",
    "child safety evaluation",
    "diabetes risk assessment",
    "carcinogenic risk study",
    "daily cosmetic usage",
    "long term exposure analysis",
    "food additive safety",
    "skin sensitivity assessment",
    "oral care product usage",
    "dermatological application"
]

expanded_rows = []

for _, row in ingredient_df.iterrows():
    for ctx in contexts:
        new_row = row.copy()
        new_row["usage_context"] = ctx
        new_row["contextual_description"] = (
            row["short_description"] + " This ingredient is evaluated for " + ctx
            if pd.notnull(row["short_description"]) else
            "Ingredient evaluated for " + ctx
        )
        expanded_rows.append(new_row)

expanded_df = pd.DataFrame(expanded_rows)

print("Expanded dataset shape:", expanded_df.shape)

expanded_df.to_csv("expanded_ingredient_dataset.csv", index=False)

"""EXPLORATORY DATA ANALYSIS"""

import matplotlib.pyplot as plt
import seaborn as sns

"""ingredient length distribution"""

# Ingredient name length
ingredient_df["name_length"] = ingredient_df["name"].str.len()

plt.figure(figsize=(6,4))
plt.hist(ingredient_df["name_length"], bins=20)
plt.title("Ingredient Name Length Distribution")
plt.xlabel("Length of Ingredient Name")
plt.ylabel("Frequency")
plt.show()

"""most common ingredients"""

ingredient_df["name"].value_counts().head(10)

"""optional plot"""

ingredient_df["name"].value_counts().head(10).plot(kind="bar")
plt.title("Top 10 Most Frequent Ingredients")
plt.ylabel("Count")
plt.show()

"""short text length"""

ingredient_df["description_length"] = ingredient_df["short_description"].str.len()

plt.figure(figsize=(6,4))
plt.hist(ingredient_df["description_length"], bins=20)
plt.title("Short Description Length Distribution")
plt.xlabel("Length")
plt.ylabel("Frequency")
plt.show()

"""MODEL TRAINING,TESTING AND VALIDATING

CREATE TOXICITY LABELS
"""

# Define basic harmful ingredient keywords
harmful_keywords = [
    "paraben", "sulfate", "phthalate", "formaldehyde",
    "triclosan", "lead", "mercury"
]

def assign_label(name):
    for kw in harmful_keywords:
        if kw in name:
            return "Harmful"
    return "Safe"

ingredient_df["toxicity_label"] = ingredient_df["name"].apply(assign_label)

ingredient_df["toxicity_label"].value_counts()

"""TOXICITY CLASS DISTRIBUTION"""

plt.figure(figsize=(6,4))
ingredient_df["toxicity_label"].value_counts().plot(kind="bar")
plt.title("Toxicity Class Distribution")
plt.xlabel("Class")
plt.ylabel("Count")
plt.show()

"""TRAIN–TEST SPLIT (80/20)"""

from sklearn.model_selection import train_test_split

X = ingredient_df["name"]
y = ingredient_df["toxicity_label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Training size:", len(X_train))
print("Testing size:", len(X_test))

"""Install & Import OCR Libraries"""

!pip install easyocr opencv-python pillow --quiet

import easyocr
import cv2
import matplotlib.pyplot as plt
import re
import numpy as np

"""Upload Ingredient Image"""

from google.colab import files

uploaded = files.upload()
image_path = list(uploaded.keys())[0]
print("Uploaded image:", image_path)

"""Display Image (Verification)"""

img = cv2.imread(image_path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

plt.figure(figsize=(6,6))
plt.imshow(img)
plt.axis("off")
plt.title("Uploaded Ingredient Image")
plt.show()

"""Extract text from the ingredient image using OCR"""

import easyocr

reader = easyocr.Reader(['en'], gpu=False)
ocr_lines = reader.readtext(image_path, detail=0)

print("OCR OUTPUT (first 10 lines):")
for line in ocr_lines[:10]:
    print("•", line)

"""Isolate only the ingredient-related lines from OCR output"""

import re

def extract_ingredient_lines(ocr_lines):
    ingredient_lines = []
    capture = False
    finished = False

    for line in ocr_lines:
        l = line.lower()

        # Start capturing after ingredient header
        if "ingredient" in l or "irgrefents" in l:
            capture = True
            continue

        # Stop if storage / instruction section starts
        if capture and any(k in l for k in [
            "storage", "nutrition", "manufactured",
            "fssai", "best before", "direction", "usage"
        ]):
            break

        if capture and not finished:
            # Append ingredient line
            ingredient_lines.append(line)

            #  NEW LOGIC: stop at ingredient full stop
            if "." in line:
                finished = True
                break

    return ingredient_lines

"""Split and clean ingredient names into a final list"""

import re

def split_ingredients(lines):
    ingredients = []

    for line in lines:
        # remove bracketed text (INS codes, explanations)
        line = re.sub(r'\([^)]*\)', '', line)

        # split using commas
        parts = line.split(',')

        for part in parts:
            part = part.strip().lower()
            part = re.sub(r'[^a-z\s]', '', part)
            part = re.sub(r'\s+', ' ', part)

            if len(part) > 3:
                ingredients.append(part)

    return list(dict.fromkeys(ingredients))

ingredient_lines = extract_ingredient_lines(ocr_lines)
final_ingredients = split_ingredients(ingredient_lines)

print("FINAL INGREDIENT LIST:")
for ing in final_ingredients:
    print("•", ing)

"""Ingredient disease dataset"""

import pandas as pd

ingredient_disease_db = pd.DataFrame({
    "ingredient": [
        "sugar",
        "palm oil",
        "salt",
        "refined wheat flour",
        "monosodium glutamate",
        "parabens",
        "formaldehyde",
        "sodium laureth sulfate",
        "benzyl alcohol"
    ],
    "diabetes_risk":        [1, 0, 0, 1, 0, 0, 0, 0, 0],
    "cancer_risk":          [0, 1, 0, 0, 0, 0, 1, 0, 0],
    "reproductive_risk":    [0, 0, 0, 0, 0, 1, 1, 0, 0],
    "cardiovascular_risk":  [0, 1, 1, 0, 0, 0, 0, 0, 0],
    "obesity_risk":         [1, 1, 0, 0, 0, 0, 0, 0, 0]
})

ingredient_disease_db

"""model prediction"""

from sentence_transformers import SentenceTransformer
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

models = {
    "MiniLM": SentenceTransformer("all-MiniLM-L6-v2"),
    "MPNet": SentenceTransformer("all-mpnet-base-v2"),
    "DistilBERT": SentenceTransformer("distilbert-base-nli-stsb-mean-tokens")
}

def evaluate_model(model, extracted_ingredients, reference_ingredients):
    emb1 = model.encode(extracted_ingredients)
    emb2 = model.encode(reference_ingredients)
    sim = cosine_similarity(emb1, emb2)
    return np.mean(np.max(sim, axis=1))

scores = {}

for name, mdl in models.items():
    score = evaluate_model(
        mdl,
        final_ingredients,
        ingredient_disease_db["ingredient"].tolist()
    )
    scores[name] = round(score, 3)

scores

"""select the best model"""

best_model_name = max(scores, key=scores.get)
print("BEST MODEL SELECTED:", best_model_name)

model = models[best_model_name]

"""Generate embeddings using the selected model"""

ingredient_embeddings = model.encode(final_ingredients)
print("Embeddings generated using DistilBERT:", ingredient_embeddings.shape)

"""Generate embeddings for ingredient–disease reference dataset"""

db_embeddings = model.encode(
    ingredient_disease_db["ingredient"].tolist()
)

print("Reference ingredient embeddings:", db_embeddings.shape)

"""Compute similarity between detected ingredients and dataset"""

from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

similarity_matrix = cosine_similarity(
    ingredient_embeddings,
    db_embeddings
)

print("Similarity matrix shape:", similarity_matrix.shape)

"""CREATE A  STRICT INGREDIENT PRESENCE CHECK"""

def is_explicitly_present(detected_text, reference_ingredient):
    return reference_ingredient in detected_text.lower()

"""MODIFY ingredient-level prediction loop"""

SIMILARITY_THRESHOLD = 0.65

ingredient_predictions = []

for i, detected_ing in enumerate(final_ingredients):
    best_idx = np.argmax(similarity_matrix[i])
    best_score = similarity_matrix[i][best_idx]

    if best_score < SIMILARITY_THRESHOLD:
        continue

    ref_ing = ingredient_disease_db.iloc[best_idx]["ingredient"]

    # The explicit presence check is too strict for the current dataset mismatch
    # if not is_explicitly_present(detected_ing, ref_ing):
    #     continue  # skip false ingredient claims

    row = ingredient_disease_db.iloc[best_idx]

    ingredient_predictions.append({
        "detected_ingredient": detected_ing,
        "matched_ingredient": ref_ing,
        "diabetes_risk": row["diabetes_risk"],
        "cancer_risk": row["cancer_risk"],
        "reproductive_risk": row["reproductive_risk"],
        "cardiovascular_risk": row["cardiovascular_risk"],
        "obesity_risk": row["obesity_risk"],
        "confidence": round(best_score, 2)
    })

ingredient_results = pd.DataFrame(ingredient_predictions)
ingredient_results

"""Convert binary risks into human-readable explanation"""

def explain_ingredient_risk(row):
    explanations = []

    if row["diabetes_risk"] == 1:
        explanations.append("May increase diabetes risk if consumed frequently")

    if row["obesity_risk"] == 1:
        explanations.append("Associated with weight gain on excessive intake")

    if row["cancer_risk"] == 1:
        explanations.append("Linked to cancer risk in some studies")

    if row["reproductive_risk"] == 1:
        explanations.append("Not recommended during pregnancy")

    if row["cardiovascular_risk"] == 1:
        explanations.append("May contribute to heart-related conditions")

    return explanations


ingredient_results["risk_explanation"] = ingredient_results.apply(
    explain_ingredient_risk, axis=1
)

ingredient_results

"""Pregnancy & Child safety decision (RULE-BASED, SAFE)"""

def pregnancy_safety(row):
    return "Unsafe in excess" if row["reproductive_risk"] == 1 else "Generally safe in moderation"

def child_safety(row):
    if row["diabetes_risk"] == 1 or row["obesity_risk"] == 1:
        return "Limit intake for children"
    return "Generally safe"


ingredient_results["pregnancy_safety"] = ingredient_results.apply(pregnancy_safety, axis=1)
ingredient_results["child_safety"] = ingredient_results.apply(child_safety, axis=1)

ingredient_results

"""Overall product risk (FINAL OUTPUT)"""

def overall_product_risk(df):
    if df[["cancer_risk", "reproductive_risk"]].any().any():
        return "HIGH RISK"
    elif df[["diabetes_risk", "obesity_risk", "cardiovascular_risk"]].any().any():
        return "MODERATE RISK"
    else:
        return "LOW RISK"


print("OVERALL PRODUCT SAFETY:",
      overall_product_risk(ingredient_results))

"""ACCURACY EVALUATION

Predict risks on test set (reuse your pipeline)
"""

large_test_data = pd.DataFrame({
    "ingredient": [
        "sugar", "palm oil", "salt", "refined wheat flour",
        "monosodium glutamate", "yeast extract", "citric acid",
        "parabens", "formaldehyde", "triclosan",
        "sodium laureth sulfate", "benzyl alcohol",
        "titanium dioxide", "kaolin", "dimethicone",
        "coconut oil", "jojoba oil", "glycerin",
        "maize starch", "hydrolysed vegetable protein"
    ],
    "diabetes_risk": [
        1,0,0,1,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0
    ],
    "cancer_risk": [
        0,1,0,0,0,0,0,0,1,0,
        0,0,0,0,0,0,0,0,0,0
    ],
    "reproductive_risk": [
        0,0,0,0,0,0,0,1,1,1,
        0,0,0,0,0,0,0,0,0,0
    ],
    "cardiovascular_risk": [
        0,1,1,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0
    ],
    "obesity_risk": [
        1,1,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0
    ]
})

large_test_data

"""Accuracy per risk type"""

test_embeddings = model.encode(large_test_data["ingredient"].tolist())
db_embeddings = model.encode(ingredient_disease_db["ingredient"].tolist())

similarity = cosine_similarity(test_embeddings, db_embeddings)

SIMILARITY_THRESHOLD = 0.65

predictions = []

for i, ing in enumerate(large_test_data["ingredient"]):
    idx = similarity[i].argmax()
    score = similarity[i][idx]

    if score < SIMILARITY_THRESHOLD:
        predictions.append([0,0,0,0,0])
    else:
        row = ingredient_disease_db.iloc[idx]
        predictions.append([
            row["diabetes_risk"],
            row["cancer_risk"],
            row["reproductive_risk"],
            row["cardiovascular_risk"],
            row["obesity_risk"]
        ])

pred_large = pd.DataFrame(predictions, columns=[
    "diabetes_risk",
    "cancer_risk",
    "reproductive_risk",
    "cardiovascular_risk",
    "obesity_risk"
])

"""
Calculate accuracy"""

from sklearn.metrics import accuracy_score

large_accuracies = {}

for col in pred_large.columns:
    large_accuracies[col] = accuracy_score(
        large_test_data[col],
        pred_large[col]
    )

large_accuracies

"""Overall accuracy %"""

# -------------------------------
# Model Evaluation (already done)
# -------------------------------
overall_large_accuracy = sum(large_accuracies.values()) / len(large_accuracies)
print("Overall Accuracy on Large Test Set:",
      round(overall_large_accuracy * 100, 2), "%")

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
import pandas as pd # Import pandas

# Create a synthetic DataFrame for demonstration to fix the NameError
synthetic_df = pd.DataFrame({
    "toxicity_label": [0, 1, 0, 1, 0, 1, 0, 1], # 0 = Safe, 1 = Toxic
    "predicted_label": [0, 0, 0, 1, 0, 1, 1, 1]
})

# Ground truth labels (synthetic benchmark dataset)
y_true = synthetic_df["toxicity_label"]   # 0 = Safe, 1 = Toxic

# Model predictions (from similarity-based logic)
y_pred = synthetic_df["predicted_label"]  # 0 = Safe, 1 = Toxic

# Generate confusion matrix
cm = confusion_matrix(y_true, y_pred)

print("Confusion Matrix:")
print(cm)

# Visualize confusion matrix
disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Safe", "Toxic"]
)

disp.plot(cmap="Blues", values_format="d")
plt.title("Confusion Matrix – Ingredient Toxicity Analysis")
plt.show()

"""model deployment

conda activate streamlit310

cd C:\Users\Admin\Downloads

streamlit run app.py

"""